server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sports-center
    username: root
    password: password
  application:
    name: SportsCenter
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: sportscenterspringboot@gmail.com
    password: lbvw kfvr mfqk pebj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
